language: python
python:

  - "3.5"
  - "3.6"  # current default Python on Travis CI
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -v tests/
  - coverage run tests/test_404_page_not_found.py
  - coverage run tests/test_api_helloworld.py 

after_success:
  - coverage report
  - coveralls